[package]
name = "nvidia_oc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
clap_complete = "4.5.8"
nvml-wrapper = "0.10.0"
nvml-wrapper-sys = "0.8.0"
sudo = "0.6.0"
